name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  preact_npm:
    name: Publish Preact to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/environment
      - name: Build library
        run: pnpm build
        working-directory: frameworks/preact
      - name: Publish library
        run: pnpm publish --provenance --access public --no-git-checks
        working-directory: frameworks/preact
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  qwik_npm:
    name: Publish Qwik to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/environment
      - name: Build library
        run: pnpm build
        working-directory: frameworks/qwik
      - name: Publish library
        run: pnpm publish --provenance --access public --no-git-checks
        working-directory: frameworks/qwik
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  solid_npm:
    name: Publish Solid to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/environment
      - name: Build library
        run: pnpm build
        working-directory: frameworks/solid
      - name: Publish library
        run: pnpm publish --provenance --access public --no-git-checks
        working-directory: frameworks/solid
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  svelte_npm:
    name: Publish Svelte to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/environment
      - name: Build library
        run: pnpm build
        working-directory: frameworks/svelte
      - name: Publish library
        run: pnpm publish --provenance --access public --no-git-checks
        working-directory: frameworks/svelte
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  vue_npm:
    name: Publish Vue to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/environment
      - name: Build library
        run: pnpm build
        working-directory: frameworks/vue
      - name: Publish library
        run: pnpm publish --provenance --access public --no-git-checks
        working-directory: frameworks/vue
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
